## Defined the default value of options which need to be provided to ibmi_tcp_interface
# Specifies whether the interface is automatically started
##################################
##     IP interface varaibles   ##
##################################
vlanid: '*NONE'
associatedLocalInterface: '*NONE'
#type_of_service: '*NORMAL' 
typeOfService: '*NORMAL'
maxTransmissionUnit: '*LIND'
autoStart: '*YES'
preferredInterface: '*NONE'
textDescription: '*BLANK'
secToWait: 0
extraParams: ''
#line_description: ''

##################################
## Line description varaibles   ##
##################################
location_code_of_ethernet_port: ''
resource_name_of_ethernet_port: ''
mac_address_of_ethernet_port: ''
# By default the command to create a line description only has two options LIND and RSRCNAME.
# For example, CRTLINETH LIND(ETHLINE) RSRCNAME(CMN03)
addition_options_for_CRTLINETH: ''

##################################
##       Route varaibles        ##
##################################
route_destination: '*DFTROUTE'
next_hop: ''
# By default the command to add routes only has two options RTEDEST and NEXTHOP. 
# For example, ADDTCPRTE RTEDEST(*DFTROUTE) NEXTHOP('9.123.97.1').
# If addtions are required, define them in addition_options_for_CRTLINETH. 
# For example addition_options_for_ADDTCPRTE: 'SUBNETMASK(*NONE) TOS(*MINCOST) MTU(*IFC)' 
addition_options_for_ADDTCPRTE: ' '
