# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
# defaults value for display_vm_info_via_powervc
project: ibm-default
project_domain: Default
user_domain: Default
verify_cert: true