#ibmi-cl-command-sample.yml 
---
- hosts: ibmi
  gather_facts: no
  collections:
   - ibm.power_ibmi
  
  tasks:
  - name: run the CL command to create a library
    ibmi_cl_command:
      cmd: crtlib lib(ansiblei)
    register: crt_lib_result
    ignore_errors: True

  - name: run the CL command to create the library again
    ibmi_cl_command:
      cmd: crtlib lib(ansiblei)
      joblog: true
    register: crt_lib_repeated_result
    ignore_errors: True

  - name: assert the repeating creation of the library failed
    assert:
      that:
        - "'CPF2111' in crt_lib_repeated_result.stderr"

  - name: run the CL command to delete the library
    ibmi_cl_command:
      cmd: dltlib ansiblei
      joblog: false
    when: "'CPC2102' in crt_lib_result.stdout or 'CPF2111' in crt_lib_repeated_result.stderr"